name: update-wiki

on:
  push:
    branches:
      - '1.**'

jobs:
  wikigen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: python3 scripts/gen-markdown-patchlist.py
      - name: Upload generated file to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "doc/generated"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.WIKI_TOKEN }}